baseURL = 'https://rulmansatis.com/'
languageCode = 'tr-tr'
title = 'RulmanSatis | Teknik Çözümler'
theme = 'ananke'

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"
